name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        
    - name: Configure build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Install PowerShell (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        # Install PowerShell on Ubuntu
        wget -q "https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb"
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
        
    - name: Install PowerShell (macOS)
      if: runner.os == 'macOS'
      run: |
        # Install PowerShell on macOS using Homebrew
        brew install --cask powershell
        
    - name: Verify PowerShell installation
      run: pwsh -v
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r e2e/requirements.txt
        
    - name: Run Rust unit tests
      run: cargo test --verbose
      
    - name: Build complgen binary
      run: cargo build --release
      
    - name: Run e2e tests
      run: pytest e2e/ --verbose